-- public.cuadrilla definition

-- Drop table

-- DROP TABLE public.cuadrilla;

CREATE TABLE public.cuadrilla (
                                  id_cuadrilla int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                  nombre_cuadrilla varchar NULL,
                                  "uuid" uuid NULL,
                                  CONSTRAINT cuadrilla_pk PRIMARY KEY (id_cuadrilla)
);


-- public.empleado definition

-- Drop table

-- DROP TABLE public.empleado;

CREATE TABLE public.empleado (
                                 id_empleado int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 nombre varchar NULL,
                                 numero_empleado varchar NULL,
                                 fecha_nacimiento date NULL,
                                 ultimo_acceso date NULL,
                                 puesto varchar NULL,
                                 ind_activo bool NULL,
                                 nombre_usuario varchar NULL,
                                 "password" varchar NULL,
                                 "uuid" uuid NULL,
                                 email varchar NULL,
                                 celular varchar NULL,
                                 fecha_creacion varchar NULL,
                                 fecha_modificacion varchar NULL,
                                 CONSTRAINT empleado_pk PRIMARY KEY (id_empleado)
);


-- public.rol definition

-- Drop table

-- DROP TABLE public.rol;

CREATE TABLE public.rol (
                            id_rol int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                            puesto varchar NULL,
                            "uuid" uuid NULL,
                            CONSTRAINT rol_pk PRIMARY KEY (id_rol)
);


-- public.empleado_cuadrilla definition

-- Drop table

-- DROP TABLE public.empleado_cuadrilla;

CREATE TABLE public.empleado_cuadrilla (
                                           id_empleado_cuadrilla int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                           "uuid" uuid NULL,
                                           id_cuadrilla int4 NOT NULL,
                                           id_empleado int4 NOT NULL,
                                           CONSTRAINT empleado_cuadrilla_pk PRIMARY KEY (id_empleado_cuadrilla),
                                           CONSTRAINT fk_id_cuadrilla FOREIGN KEY (id_cuadrilla) REFERENCES public.cuadrilla(id_cuadrilla),
                                           CONSTRAINT fk_id_empleado FOREIGN KEY (id_empleado) REFERENCES public.empleado(id_empleado)
);